# 1. Toon alle windmolens
# Datasource: sparql@https://api.labs.kadaster.nl/datasets/kadaster/Kadaster-Registratieve-Linked-Data/services/registraties/sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
WHERE {
  ?molen a <http://brt.basisregistraties.overheid.nl/def/top10nl#Windmolen>.
  ?molen rdfs:label ?wktLabel.
  ?molen geo:hasGeometry ?geometry.
  ?geometry geo:asWKT ?wkt.
}